# Generated by Django 2.0 

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20180127_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver_info',
            name='driverLicensePicture',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='driver_info',
            name='driverProfilePicture',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
