# Generated by Django 2.0 

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_auto_20180131_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='garbageDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garbagePicture', models.ImageField(default='', upload_to='')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('geotag', models.TextField()),
                ('user_id', models.IntegerField()),
                ('time', models.CharField(max_length=25)),
                ('date', models.CharField(max_length=25)),
            ],
        ),
    ]
