# Generated by Django 2.0 

from django.db import migrations # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_auto_20180223_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver_info',
            name='driverAddress',
        ),
    ]
