# Generated by Django 2.0 

from django.db import migrations, models # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_auto_20180319_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garbagedetails',
            name='garbagePicture',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='garbagedetails',
            name='garbagePictureVerification',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
    ]
