# Generated by Django 5.2.6 on 2025-09-19 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='garbageDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garbagePicture', models.ImageField(default='', upload_to='')),
                ('garbagePictureVerification', models.ImageField(blank=True, default='', null=True, upload_to='')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('geotag', models.TextField()),
                ('user_id', models.IntegerField()),
                ('time', models.CharField(max_length=25)),
                ('driver_id', models.IntegerField(blank=True, null=True)),
                ('date', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name_plural': 'Garbage Details',
            },
        ),
        migrations.CreateModel(
            name='schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('address', models.TextField(blank=True, null=True)),
                ('days', models.IntegerField()),
                ('community', models.BooleanField()),
                ('noOfHouses', models.IntegerField(blank=True, null=True)),
                ('specialInst', models.TextField(blank=True, null=True)),
                ('driver_id', models.IntegerField(blank=True, null=True)),
                ('landmark', models.CharField(blank=True, max_length=30, null=True)),
                ('driver_completion', models.IntegerField(blank=True, null=True)),
                ('user_approval', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Schedule',
            },
        ),
        migrations.CreateModel(
            name='user_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userProfilePicture', models.ImageField(default='C:\\Users\\Admin\\Pictures\\Saved Pictures\\s1.jpg', upload_to='C:\\Users\\Admin\\Pictures\\Saved Pictures\\s1.jpg')),
                ('userName', models.CharField(max_length=25)),
                ('userDay', models.IntegerField()),
                ('userMonth', models.IntegerField()),
                ('userYear', models.IntegerField()),
                ('userAddress', models.TextField()),
                ('userEmail', models.CharField(max_length=50)),
                ('userPhno', models.BigIntegerField()),
                ('userUname', models.CharField(max_length=25)),
                ('userPwrd', models.CharField(max_length=25)),
                ('userType', models.IntegerField()),
                ('isLoggedIn', models.BooleanField()),
                ('device_id', models.CharField(blank=True, max_length=50, null=True)),
                ('notifications', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'User Info',
            },
        ),
        migrations.CreateModel(
            name='driver_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driverLicPicture', models.ImageField(default='', upload_to='')),
                ('driverDayLIC', models.IntegerField()),
                ('driverMonthLIC', models.IntegerField()),
                ('driverYearLIC', models.IntegerField()),
                ('driverLino', models.CharField(max_length=15)),
                ('driverVeno', models.CharField(max_length=10)),
                ('approved', models.BooleanField(blank=True, null=True)),
                ('driverArea', models.CharField(blank=True, max_length=20, null=True)),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.user_details')),
            ],
        ),
    ]
