# Generated by Django 5.2.6 on 2025-09-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='notifications',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='userProfilePicture',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
