# Generated by Django 5.2.6 on 2025-10-03 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_driverdetails_pickupschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garbagedetails',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='garbagedetails',
            name='longitude',
        ),
    ]
