# Generated by Django 5.2.6 on 2025-10-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_remove_garbagedetails_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garbagedetails',
            name='geotag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
