# Generated by Django 5.2.6 on 2025-10-03 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_garbagedetails_geotag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garbagedetails',
            name='user_id',
            field=models.IntegerField(blank=True, max_length=255, null=True),
        ),
    ]
