# Generated by Django 5.2.6 on 2025-10-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_garbagedetails_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garbagedetails',
            name='date',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='garbagedetails',
            name='time',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
