# Generated by Django 2.0

from django.db import migrations, models # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_driver_info_driverlicensepicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver_info',
            name='driverLicensePicture',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='driver_info',
            name='driverProfilePicture',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='userProfilePicture',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
