# Generated by Django 2.0 

from django.db import migrations # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_schedule_noofhouses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='driver_id',
        ),
    ]
